Update dev_firebase_depoy.yml

diff --git a/.github/workflows/dev_firebase_depoy.yml b/.github/workflows/dev_firebase_depoy.yml
--- a/.github/workflows/dev_firebase_depoy.yml
+++ b/.github/workflows/dev_firebase_depoy.yml
@@ -7,14 +7,14 @@ on:
 jobs:
   build:
     runs-on: ubuntu-latest
-    env:
-      GOOGLE_APPLICATION_CREDENTIALS: google-application-credentials.json
+   # env:
+   #   GOOGLE_APPLICATION_CREDENTIALS: google-application-credentials.json
 
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
 
-      - name: create firebase config file 
+      - name: Create firebase config file 
         run: |
            echo "creating firebase_config.dart"
            mkdir lib/backend/firebase
@@ -33,21 +33,21 @@ jobs:
       - name: Build Flutter for web
         run: flutter build web
         
-      - name: Prepare Google Application Credentials
-        shell: bash
-        run: |
-          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_BASE64 }}" | base64 --decode > "google-application-credentials.json"
+#      - name: Prepare Google Application Credentials
+#        shell: bash
+#        run: |
+#          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_BASE64 }}" | base64 --decode > "google-application-credentials.json"
 
       - name: Deploy to Firebase Hosting
-        # env:
+        env:
+          FIREBASE_TOKEN: ${{ secrets.DEV_FIREBASE_TOKEN }}
           # GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.FIREBASE_DEV_GOOGLE_APPLICATION_CREDENTIALS }}          
-          # FIREBASE_TOKEN: ${{ secrets.DEV_FIREBASE_TOKEN }}
           # GOOGLE_APPLICATION_CREDENTIALS: ${{ runner.temp }}/firebase-service-account.json
           # echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > $GOOGLE_APPLICATION_CREDENTIALS
         run: |
           npm install -g firebase-tools
           firebase deploy --only hosting --project my-demo-app-dev-9f4c3
-      - name: Remove credentials file
-        if: success() || failure()
-        run: |
-          rm google-application-credentials.json
+#      - name: Remove credentials file
+#        if: success() || failure()
+#        run: |
+#          rm google-application-credentials.json
